sudo: required

services:
  - docker

before_install:
  - docker build -t 0426abhishek/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run 0426abhishek/multi-docker npm test -- --coverage --watchAll=false

after_sucess:
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker

# Login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them into docker hub after docker login
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker

# Deploy Application to AWS Server into ElasticBeanStalk
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-west-1-306476627547" (S3 bucket name)
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"