sudo: required

services:
  - docker

before_install:
  - docker build -t 0426abhishek/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run 0426abhishek/multi-docker npm test -- --coverage --watchAll=false

after_sucess:
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker

# Login into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them into docker hub after docker login
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker